### ISSUE TITLE
Export came out as just a black screen

### ISSUE THREAD

**Issue by mariotee** [Nasso/urmusic-desktop#12]
[ffmpeg_output.log](https://github.com/nasso/urmusic-desktop/files/3159550/ffmpeg_output.log)
[urmusic.err.log](https://github.com/nasso/urmusic-desktop/files/3159551/urmusic.err.log)

attached logs
waited 1+ hour to render and then i got nothin' lol

**Comment by nasso** [comment]
Try opening the video file with VLC
Many players can't read it because for some reason it is encoded with a 4:4:4 chroma, and it isn't widely supported

**Comment by mariotee** [comment]
nice! yeah. it works on VLC no problem.
and if anyone else stumbles onto this, it uploads to YouTube no problem.

thank you!
