### ISSUE TITLE
TUTORIAL How to open "urmusic-desktop-alpha-0.4.0.jar"

### ISSUE THREAD

**Issue by devteam21** [Nasso/urmusic-desktop#14]
SORRY NASSO "JUST A LITTLE HELP FROM INDONESIAN PEOPLE" :)
Sorry nasso, i wanna asking that version 0.4.0 motion blur is default disable? right?
if default it's oke i just wanna know my laptop is error or not, because says have motion blur. thanks.

For a while i create a file opener. bat (Batch extension) to run-jar Urmusic.

Such Bug I found when-jar needed an older version (version 211) then I tried to decrease the RE version from version 212 to version 211 ~ it worked!

How to build opener. Bat:
1. Download and install RE 211 (required version of IT)
2. Create a new file, I give it name  "opener " with batch extension
3. File output must be opener. bat
4. Open "opener. bat " Then give it a little code "javaw.exe -jar urmusic-desktop-alpha-0.4.0. jar"
5. Save the Urmusic folder
6. Click the opener. bat and see Urmusic is open:)

STILL CONFUSED?
Download and instal java 211 [here](https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)

Download my opener.bat [here](https://drive.google.com/open?id=1uXc6MGk7ooYwm4XahgKA7GUgQf41cOrl)
then paste in ur directory urmusic, and double clicks opener.bat ..

SEE MY [PICTURE](https://buzzuploads.com/images/2019/06/15/ssssss.png)

Add my instagram for make new friends 👍 
Tutorial by [Devaks](https://www.instagram.com/devaldiakbar/)

**Comment by nasso** [comment]
Please edit [the wiki](https://github.com/nasso/urmusic-desktop/wiki) if you want to add a tutorial or something similar!
