### ISSUE TITLE
I can't open the sofwareeee PLEASE HELP

### ISSUE THREAD

**Issue by orbo11** [Nasso/urmusic-desktop#3]
Here's the error log

[urmusic.err.log](https://github.com/nasso/urmusic-desktop/files/1966539/urmusic.err.log)

ps: I'm on macbook pro and i downloaded Java SE JDK but when i try to open the jar file it says {The java file could not be launched}

Please help

**Comment by nasso** [comment]
JavaFX seems to be unable to find a CSS file... thats weird.
This probably comes from the  JavaFX implementation on Mac...
I can't really help here as I don't have any Apple devices..
You can try to build it from the source yourself though, and see if it can be fixed. I accept pull requests.

**Comment by nashatoth** [comment]
My greetings to you from Syria why I did not work for the program when you unpack it, but I do not work, I hope solution and thanks

**Comment by nasso** [comment]
@nashatoth Please create a new issue for your problem, thanks!

**Comment by nashatoth** [comment]
Here's the error log

Hello problem is that when i open the program come out directly and give me this txt file i have uploaded it on the media see    
http://www.mediafire.com/file/bhhfb34k2j5hdnm/urmusic.err.log

**Comment by nasso** [comment]
Thanks for your report; will do more tests on other platforms for futute releases!

**Comment by nashatoth** [comment]
Please fix the problem and I am currently using the version on the browser but I want the version on the computer

**Comment by nasso** [comment]
The next version is in development and it's a complete rewrite; I'll make sure the issue will not stay.

**Comment by nashatoth** [comment]
Thank you my friend, greetings to you from Syria
