### ISSUE TITLE
HELP! Can't open my .urm files.

### ISSUE THREAD

**Issue by ITMPD** [Nasso/urmusic-desktop#5]
I have a project in which I have been working on for like 3 hours, and I saved it alot like every 3 minutes or so. I saved it for later, but when I try to open the saved file again, it just doesn't open ;-; I also tried opening the other .urm files
it doesn't open too, but not all of them. I'm guessing that this have something to do with the file size. Apparently, the .urm file that is like 5kb opened, but the file that im trying to open is like 3,912kb

when i try to open the 3912 kb one, it just doesn't open. like nothing appeared. the application doesn't crash and it doesn't freeze either?

are there anyways to fix this so I can open them?

**Comment by nasso** [comment]
The software is known to be broken on most parts. I am currently working on the next version, you can find it on GitLab: https://gitlab.com/nasso/urmusic5-core
Although this is far from being finished.
