### ISSUE TITLE
Im having trouble with exporting my song and it showing up in general

### ISSUE THREAD

**Issue by FriedKelp** [Nasso/urmusic-desktop#8]
When I heard about this I was immediately eager to get this and take a look at it, but sadly it shows up as a black screen for me even when I export music. Nothing shows up. Im not sure if its for windows only but I use a mac. Im not sure if the website is shut down or doesn't work anymore... but please reply back because I want to know how to use this.

**Comment by nasso** [comment]
I haven't tested the program on Mac because i don't own any, but you should try to read the video with VLC.
Though I didn't include the ffmpeg binaries for mac so unless you're using your own, it shouldn't be able to even export a video.
